COMP3297/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
import SDP.views
from django.contrib.auth import views as auth_views
from SDP.login_form import LoginForm

urlpatterns = [
                  url(r'^$', SDP.views.home),
                  url(r'^admin/', admin.site.urls),
                  url(r'^home/$', SDP.views.home),
                  url(r'^home_instructor/$', SDP.views.home_instructor),
                  url(r'^home_hr/$', SDP.views.home_hr),
                  url(r'^home_admin/$', SDP.views.home_admin),
                  url(r'^course/(?P<course_id>\d+)', SDP.views.course),
                  url(r'^modify_course/(?P<course_id>\d+)', SDP.views.modify_course),
                  url(r'^modify_course_order/(?P<course_id>\d+)', SDP.views.modify_course_order),
                  url(r'^enrol/(?P<course_id>\d+)', SDP.views.enrol),
                  url(r'^drop/(?P<course_id>\d+)', SDP.views.drop),
                  url(r'^category/(?P<cid>\d+)', SDP.views.category),
                  url(r'^create/', SDP.views.create),
                  url(r'^create_module/(?P<course_id>\d+)', SDP.views.create_module),
                  url(r'^create_component/(?P<module_id>\d+)/(?P<type>\w+)', SDP.views.create_component),
                  url(r'^logout/$', auth_views.logout, {'next_page': '/login'}),
                  url(r'^login/$', auth_views.login, {'template_name': 'login.html', 'authentication_form': LoginForm},
                      name='login'),
                  url(r'^register/$', SDP.views.register),
                  url(r'^record/$', SDP.views.record),
                  url(r'^role/$', SDP.views.role),
                  url(r'^designate/$', SDP.views.designate),
                  url(r'^control_access/$', SDP.views.control_access),
                  url(r'^open_course/(?P<course_id>\d+)', SDP.views.open_course),
                  url(r'^next_module/(?P<course_id>\d+)', SDP.views.next_module),
                  url(r'^manage_category/$', SDP.views.manage_category),
                  url(r'^no_permission', SDP.views.no_permission)

              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

SDP/models.py
from django.db import models
from django.contrib.auth.models import User
from embed_video.fields import EmbedVideoField

# Create your models here.


COMPONENT_TYPEs = (('file', 'file'), ('image', 'image'), ('text', 'text'), ('quiz', 'quiz'), ('video', 'video'))


class Course(models.Model):
    course_id = models.AutoField(primary_key=True)
    title = models.TextField(max_length=127)
    description = models.TextField(max_length=2000)
    open = models.BooleanField(default=False)
    category = models.ForeignKey('Category')
    instructor = models.ForeignKey('Employee')

    def __str__(self):
        return self.title


class Employee(models.Model):
    employee_id = models.AutoField(primary_key=True)
    employee_name = models.CharField(max_length=127)
    user = models.ForeignKey(User)

    def __str__(self):
        return self.employee_name


class Instructor(models.Model):
    employee = models.ForeignKey(Employee)

    class Meta:
        permissions = (
            ("instructor", "Instructor permissions"),
        )


class Administrators(models.Model):
    employee = models.ForeignKey(Employee)

    class Meta:
        permissions = (
            ("admin", "Administrator permissions"),
        )


class HR(models.Model):
    employee = models.ForeignKey(Employee)

    class Meta:
        permissions = (
            ("HR", "HR permissions"),
        )


class Enrollment(models.Model):
    enrollment_id = models.AutoField(primary_key=True)
    course = models.ForeignKey('Course')
    employee = models.ForeignKey('Employee')
    progress = models.IntegerField(default=1)
    completed = models.BooleanField(default=False)
    completed_date = models.DateField(null=True, blank=True)

    def __str__(self):
        return self.course.title


class Module(models.Model):
    module_id = models.AutoField(primary_key=True)
    title = models.TextField(max_length=127)
    course = models.ForeignKey('Course')
    order = models.IntegerField()

    def __str__(self):
        return self.course.title + ' - Module ' + str(self.module_id)


class Component(models.Model):
    component_id = models.AutoField(primary_key=True)
    module = models.ForeignKey('Module')
    order = models.IntegerField()
    title = models.CharField(max_length=127)
    type = models.CharField(max_length=127, choices=COMPONENT_TYPEs, default='text')
    text_content = models.TextField(default='', null=True, blank=True)
    image_content = models.ImageField(upload_to='uploads', null=True, blank=True)
    file_content = models.FileField(upload_to='uploads', null=True, blank=True)
    video_url = EmbedVideoField(null=True, blank=True)
    question = models.CharField(max_length=4096, null=True, blank=True)
    answer = models.CharField(max_length=4096, null=True, blank=True)

    def __str__(self):
        return self.module.__str__() + ' - ' + self.title


class Category(models.Model):
    category_id = models.AutoField(primary_key=True)
    category_name = models.CharField(max_length=127)

    def __str__(self):
        return self.category_name

SDP/views.py
import re

import datetime
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required, permission_required
from django.http import HttpResponseRedirect, HttpResponse
from django.contrib.auth.models import User, Permission
from django.db.models import F

from SDP.models import Category
from SDP.models import Course
from SDP.models import Module
from SDP.models import Component
from SDP.models import Enrollment
from SDP.models import Employee
from SDP.models import Administrators
from SDP.models import Instructor
from SDP.models import HR

from .create_course_form import CourseInfoForm, ModuleInfoForm, \
    TextComponentInfoForm, ImageComponentInfoForm, FileComponentInfoForm, VideoComponentInfoForm, QuizComponentInfoForm
from .login_form import RegisterForm
from .role_form import DesignateForm, ControlAccessForm, RecordForm, AddCategoryForm


def whoami(uid):
    return Employee.objects.filter(user_id__exact=uid)[0]


@login_required(login_url="/login/")
def home(request):
    me = whoami(request.user.id)
    enrollment_info = Enrollment.objects.filter(employee=me)
    if enrollment_info:
        taking_courses = []
        for enrollment in enrollment_info.filter(completed=False):
            taking_courses.append(enrollment.course)
        completed_courses = []
        for enrollment in enrollment_info.filter(completed=True):
            completed_courses.append((enrollment.course, enrollment.completed_date))
    else:
        taking_courses = []
        completed_courses = []
    return render(request, 'home.html', {'categories': Category.objects.all(),
                                         'whoami': me,
                                         'role': "participant",
                                         'taking_courses': taking_courses,
                                         'completed_courses': completed_courses})


@login_required(login_url="/login/")
@permission_required('SDP.instructor', login_url="/no_permission")
def home_instructor(request):
    me = whoami(request.user.id)
    teaching_info = Course.objects.filter(instructor=me)
    if teaching_info:
        teaching_courses = []
        for teaching in teaching_info:
            teaching_courses.append(teaching)
    else:
        teaching_courses = None
    return render(request, 'home_instructor.html', {'whoami': me,
                                                    'role': "instructor",
                                                    'teaching_courses': teaching_courses})


@login_required(login_url="/login/")
@permission_required('SDP.HR', login_url="/no_permission")
def home_hr(request):
    me = whoami(request.user.id)
    return render(request, 'home_hr.html', {'whoami': me,
                                            'role': "HR"})


@login_required(login_url="/login/")
@permission_required('SDP.admin', login_url="/no_permission")
def home_admin(request):
    me = whoami(request.user.id)
    return render(request, 'home_administrator.html', {'whoami': me,
                                                       'role': "administrator"})


@login_required(login_url="/login/")
@permission_required('SDP.admin', login_url="/no_permission")
def designate(request):
    me = whoami(request.user.id)
    if request.method == 'POST':
        form = DesignateForm(request.POST)
        if form.is_valid():
            username = request.POST['username']
            user = User.objects.filter(username=username)
            if not user:
                return HttpResponse("No such user.")
            employee = Employee.objects.filter(user=user[0])
            if Instructor.objects.filter(employee=employee[0]):
                return HttpResponse("User is already a instructor.")
            permission = Permission.objects.get(codename='instructor')
            user[0].user_permissions.add(permission)
            new_instructor = Instructor.objects.create(employee=employee[0])
            new_instructor.save()
            return redirect("/home_admin/")
    else:
        form = DesignateForm()
    return render(request, 'designate.html', {'whoami': me,
                                              'role': 'administrator',
                                              'form': form})


@login_required(login_url="/login/")
@permission_required('SDP.admin', login_url="/no_permission")
def control_access(request):
    me = whoami(request.user.id)
    if request.method == 'POST':
        form = ControlAccessForm(request.POST)
        if form.is_valid():
            username = request.POST['username']
            user = User.objects.filter(username=username)
            if not user:
                return HttpResponse("No such user.")

            if 'is_active' in request.POST:
                is_active = True
            else:
                is_active = False
            new_status = user.update(is_active=is_active)
            return redirect("/home_admin/")
    else:
        form = ControlAccessForm()
    return render(request, 'control_acces.html', {'whoami': me,
                                                  'role': 'administrator',
                                                  'form': form})


@login_required(login_url="/login/")
def category(request, cid):
    me = whoami(request.user.id)
    select_category = Category.objects.filter(category_id=cid)[0]
    course_in_category = Course.objects.filter(category__category_id=cid, open=True)
    return render(request, 'category.html', {'categories': Category.objects.all(),
                                             'whoami': me,
                                             'select_category': select_category,
                                             'role': 'participant',
                                             'course_in_category': course_in_category})


@login_required(login_url="/login/")
def course(request, course_id):
    course = Course.objects.filter(course_id=course_id)
    me = whoami(request.user.id)
    if course:
        if not Enrollment.objects.filter(employee=me, course=course[0]):
            return HttpResponse("You haven't enrolled in this course.")
        select_course = course[0]
        progress = Enrollment.objects.filter(course=select_course, employee=me)[0].progress
        total = Module.objects.filter(course=select_course).count()
        module_in_course = Module.objects.filter(course__course_id=course_id, order=progress)
        module_with_components = []
        for module in module_in_course:
            module_with_components.append(
                (module, Component.objects.filter(module__module_id=module.module_id).order_by('order')))
    else:
        HttpResponse("No such course")
    return render(request, 'course.html', {'categories': Category.objects.all(),
                                           'whoami': me,
                                           'role': 'participant',
                                           'select_course': select_course,
                                           'total': total,
                                           'module_with_components': module_with_components})


@login_required(login_url="/login/")
@permission_required('SDP.instructor', login_url="/no_permission")
def modify_course(request, course_id):
    me = whoami(request.user.id)
    course = Course.objects.filter(course_id=course_id)
    if course:
        select_course = course[0]
        if select_course.instructor != me:
            return HttpResponse("You are not allow to modify this course.")
        module_in_course = Module.objects.filter(course__course_id=course_id).order_by('order')
        module_with_components = []
        for module in module_in_course:
            module_with_components.append(
                (module, Component.objects.filter(module__module_id=module.module_id).order_by('order')))
    else:
        HttpResponse("No such course")
    return render(request, 'modify_course.html', {'categories': Category.objects.all(),
                                                  'whoami': me,
                                                  'select_course': select_course,
                                                  'role': 'instructor',
                                                  'module_with_components': module_with_components})


@login_required(login_url="/login/")
@permission_required('SDP.instructor', login_url="/no_permission")
def modify_course_order(request, course_id):
    me = whoami(request.user.id)
    course = Course.objects.filter(course_id=course_id)
    if course:
        if request.method == 'POST' and request.POST['change'] == "change":
            for key, pos in request.POST.items():
                if key.startswith("order_m"):
                    module_key = int(key[7:])
                    Module.objects.filter(module_id__exact=module_key).update(order=int(pos))
                if key.startswith("order_c"):
                    component_key = int(key[7:])
                    Component.objects.filter(component_id__exact=component_key).update(order=int(pos))
            return redirect("/modify_course/" + course_id)
        else:
            select_course = course[0]
            module_in_course = Module.objects.filter(course__course_id=course_id).order_by('order')
            module_with_components = []
            for module in module_in_course:
                module_with_components.append(
                    (module, Component.objects.filter(module__module_id=module.module_id).order_by('order')))
    else:
        HttpResponse("No such course")
    return render(request, 'modify_course_order.html', {'categories': Category.objects.all(),
                                                        'whoami': me,
                                                        'role': 'instructor',
                                                        'select_course': select_course,

SDP/templates/category.html
<!DOCTYPE html>
<html>
    {% include "head.html" %}
<body>

<div class="container">

    {% include "header.html" %}

    {% include "nav.html" %}

    <article>
        <h1>{{ select_category.get_category_name_display  }}</h1>
        <div class="flexbox">
            {% for item in course_in_category %}
                <div class="course_container">
                <a href="/course/{{ item.course_id }}">{{ item.title }}</a>
                <a class="enrol" href="/enrol/{{ item.course_id }}">Enrol/Retake</a>
                <p>{{ item.description }}</p>
                <p>Instructor : {{ item.instructor }}</p>
            </div>
            {% endfor %}
        </div>
    </article>


</div>

</body>
</html>

SDP/templates/create_component.html
<!DOCTYPE html>
<html>
{% include "head.html" %}
<body>

<div class="container">

    {% include "header.html" %}

    {% include "nav_instructor.html" %}

    <article>
        <form method="post" action="/create_component/{{ module_id }}/{{ type }}" enctype="multipart/form-data">
            {% csrf_token %}
            <h2>{{ module_title }}</h2>
            {% if not type == "quiz" %}
                <table>
                    <tr>
                        <td>{{ form.title.label_tag }}</td>
                        <td>{{ form.title }}</td>
                    </tr>
                    <tr>
                        <td>{{ form.content.label_tag }}</td>
                        <td>{{ form.content }}</td>
                    </tr>
                </table>
            {% endif %}
            {% if type == "quiz" %}
                <table>
                    <tr>
                        <td>{{ form.title.label_tag }}</td>
                        <td>{{ form.title }}</td>
                    </tr>
                    <tr>
                        <td>{{ form.question.label_tag }}</td>
                        <td>{{ form.question }}</td>
                    </tr>
                    <tr>
                        <td>{{ form.answer.label_tag }}</td>
                        <td>{{ form.answer }}</td>
                    </tr>
                </table>
            {% endif %}
            <input type="submit" value="create"/>
        </form>
    </article>


</div>

</body>
</html>

SDP/templates/create_module.html
<!DOCTYPE html>
<html>
{% include "head.html" %}
<body>

<div class="container">

    {% include "header.html" %}

    {% include "nav_instructor.html" %}

    <article>
        <form method="post" action="/create_module/{{ course_id }}">
            {% csrf_token %}
            <h2>{{ course_title }}</h2>
            <table>
                <tr>
                    <td>{{ form.title.label_tag }}</td>
                    <td>{{ form.title }}</td>
                </tr>
            </table>

            <input type="submit" value="create"/>
        </form>
    </article>


</div>

</body>
</html>

SDP/templates/head.html
<head>
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static "style.css" %}">
    <script src="{% static "jquery-3.1.1.js" %}"></script>
    <script src="{% static "util.js" %}"></script>
</head>

SDP/templates/header.html
<header>
    <div class="header-container-center"><h1>SDP system</h1></div>
    <div class="header-container-right">Dear {{ whoami.employee_name }}.| Current role: {{ role }} , <a class="button" href="/role/">change role</a>
        |<a class="button" href="/logout/">logout</a></div>
</header>

SDP/templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

SDP/templates/login.html
<!DOCTYPE html>
<html>
{% include "head.html" %}
<body>

<div class="container">

    {% include "header_login.html" %}


    <div class="login_box">
        {% block content %}
            {% if form.errors %}

                <p>Your username and password didn't match. Please try again.</p>
            {% endif %}

            {% if next %}
                {% if user.is_authenticated %}

                    <p>Your AB account doesn't have access to this page. To proceed,
                        please login with an account that has access.</p>
                {% else %}

                    <h1>Please enter your AB ID and password.</h1>
                {% endif %}
            {% endif %}

            <form method="post" action="/login/">
                {% csrf_token %}
                <table>
                    <tr>
                        <td>{{ form.username.label_tag }}</td>
                        <td>{{ form.username }}</td>
                    </tr>
                    <tr>
                        <td>{{ form.password.label_tag }}</td>
                        <td>{{ form.password }}</td>
                    </tr>
                </table>

                <input type="submit" value="login"/>
                <input type="hidden" name="next" value="{{ next }}"/>
                <a href="/register/">Register as SDP user with an AB ID</a>
            </form>
        {% endblock %}
    </div>


</div>

</body>
</html>

SDP/templates/manage_category.html
<!DOCTYPE html>
<html>
{% include "head.html" %}
<body>

<div class="container">

    {% include "header.html" %}

    {% include "nav_administrator.html" %}

    <article>
        <form method="post" action="/manage_category/">
            {% csrf_token %}
            <h2>Add a category</h2>
            <table>
                <tr>
                    <td>{{ form.catname.label_tag }}</td>
                    <td>{{ form.catname }}</td>
                </tr>
            </table>

            <input type="submit" value="Create"/>
        </form>
    </article>


</div>

</body>
</html>

SDP/templates/nav.html
<nav>
    <ul>
        <li><a href="/home">Home</a></li>
        <li><a class="subnav_click" href="#">Category</a></li>
        <ul class="subnav">
            {% for item in categories %}
                <li><a href="/category/{{ item.category_id }}">{{ item.category_name }}</a></li>
            {% endfor %}
        </ul>
    </ul>
</nav>

SDP/templates/nav_hr.html
<nav>
    <ul>
        <li><a href="/home_hr">Home</a></li>
        <li><a href="/record">Check completed course</a></li>
    </ul>
</nav>

SDP/templates/nav_instructor.html
<nav>
    <ul>
        <li><a href="/home_instructor">Home</a></li>
        <li><a href="/create/">Create new course</a></li>
    </ul>
</nav>

SDP/templates/quiz.html
<!DOCTYPE html>
<html>
{% include "head.html" %}
<body>

<div class="container">

    {% include "header.html" %}


    {% include "nav.html" %}

    <article>

        <h1>{{ select_course.title }}</h1>

        {% for module in module_with_components %}
            <div class="module">
                <h3>Module {{ module.0.order }}</h3>
                {% for component in module.1 %}
                    {% if component.type == 'text' %}
                        <p>{{ component.title }}</p>
                        <p>{{ component.text_content }}</p>
                    {% endif %}
                    {% if component.type == 'image' %}
                        <p>{{ component.title }}</p>
                        <img width="100%" src="{{ component.image_content.url }}">
                    {% endif %}
                    {% if component.type == 'file' %}
                        <a href="{{ component.file_content.url }}">{{ component.title }}</a>
                    {% endif %}
                {% endfor %}
            </div>
        {% endfor %}

    </article>


</div>

</body>
</html>

SDP/templates/register.html
<!DOCTYPE html>
<html>
{% include "head.html" %}
<body>

<div class="container">

    {% include "header_login.html" %}


    <div class="login_box">
        {% block content %}
            <form method="post" action="/register/">
                {% csrf_token %}
                <table>
                    <tr>
                        <td>{{ form.employee_name.label_tag }}</td>
                        <td>{{ form.employee_name }}</td>
                    </tr>
                    <tr>
                        <td>{{ form.username.label_tag }}</td>
                        <td>{{ form.username }}</td>
                    </tr>
                    <tr>
                        <td>{{ form.password.label_tag }}</td>
                        <td>{{ form.password }}</td>
                    </tr>
                    <tr>
                        <td>{{ form.password_again.label_tag }}</td>
                        <td>{{ form.password_again }}</td>
                    </tr>
                </table>

                <input type="submit" value="Submit"/>
            </form>
        {% endblock %}
    </div>

</div>

</body>
</html>

SDP/templates/role.html
<!DOCTYPE html>
<html>
{% include "head.html" %}
<body>

<div class="container">

    {% include "header.html" %}


    <div class="login_box">
        <table>

            <tr><a href="/home">Login as participant.</a></tr>
            {% if is_instructor == True %}
                <tr><a href="/home_instructor">Login as instructor.</a></tr>
            {% endif %}
            {% if is_HR == True %}
                <tr><a href="/home_hr">Login as HR.</a></tr>
            {% endif %}
            {% if is_admin == True %}
                <tr><a href="/home_admin">Login as administrator.</a></tr>
            {% endif %}
        </table>
    </div>


</div>

</body>
</html>